[project]
name = "iris-mcp"
version = "0.1.0"
description = "DFIR-IRIS MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dfir-iris-client>=2.0.4",
    "fastmcp>=2.13.2",
]


[project.scripts]
iris-mcp = "iris_mcp:run"
